---
resources:
  # Um objeto que representa este repositório
  ## Apenas no CI os repositórios são baixados automaticamente
  ## Em workflows, você precisa definir os repositórios e solicitar o download
  - name: meetup-app-sec
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: fewbits/meetup-app-sec
      branch: master

  # Integração com a Cloudflare (basicamente e-mail e chave da API)
  - name: cloudflare
    type: integration
    integration: cloudflare

  # Informações sobre a imagem de Sistema Operacional oficial da empresa
  - name: os_image_version
    type: version
    versionTemplate:
      versionName: "0"

jobs:
  # Atualizar o DNS do ambiente de Testes
  - name: dns_test
    type: runSh
    steps:
      # Vou usar este repositório
      - IN: meetup-app-sec
        switch: on
      # Essa atividade está associada com o IP da VM de Testes
      ## Se o IP mudar, precisamos executar esta atividade novamente
      - IN: vm_test
        switch: on
      # Integração com a CloudFlare (basicamente e-mail e chave de API)
      - IN: cloudflare
        switch: off
      # Agora é a tarefa...
      - TASK:
          name: dns_test
          runtime:
            options:
              env:
                - meetup_env: test
          script:
            # Solicito dados do repositório
            - pushd $(shipctl get_resource_state "meetup-app-sec")/ansible
            # Chamo a automação
            - ansible-playbook dns_update.yml --extra-vars "meetup_env=${meetup_env} meetup_vm_ip=${external_ip} cloudflare_email=${cloudflare_email} cloudflare_api=${cloudflare_api}"

  # Atualizar o DNS do ambiente de Produção
  - name: dns_prod
    type: runSh
    steps:
      # Vou usar este repositório, mas não será um gatilho
      - IN: meetup-app-sec
        switch: off
      # Essa atividade está associada com o IP da VM de Produção
      ## Se o IP mudar, precisamos executar esta atividade novamente
      - IN: vm_prod
        switch: on
      # Mais um gatilho: Tarefa de criação da VM de Produção
      - IN: vm_prod_create
      # Integração com a CloudFlare (basicamente e-mail e chave de API)
      - IN: cloudflare
        switch: off
      # Agora é a tarefa...
      - TASK:
          name: dns_prod
          runtime:
            options:
              env:
                - meetup_env: prod
          script:
            # Solicito dados do repositório
            - pushd $(shipctl get_resource_state "meetup-app-sec")/ansible
            # Chamo a automação
            - ansible-playbook dns_update.yml --extra-vars "meetup_env=${meetup_env} meetup_vm_ip=${external_ip} cloudflare_email=${cloudflare_email} cloudflare_api=${cloudflare_api}"

  # Criar imagem oficial da empresa
  - name: os_image_create
    type: runSh
    steps:
      # Vou usar este repositório (é gatilho)
      - IN: meetup-app-sec
        switch: on
      # Integração com a Google Cloud (não é gatilho)
      - IN: google_cloud
        switch: off
      # A saída é a versão da imagem
      - OUT: os_image_version
      # Após a criação da imagem, precisamos utilizá-la no ambiente de testes
      - OUT: vm_test_create
      # Agora é a tarefa...
      - TASK:
          name: os_image_create
          runtime:
            options:
              env:
                - GCE_CREDENTIALS_FILE_PATH: "gcp_key.json"
          script:
            # Solicito dados do repositório
            - pushd $(shipctl get_resource_state "meetup-app-sec")/packer
            # Versiono o nome da imagem de acordo com a versão do job
            - shipctl replace official-image.json
            # Solicito informações de autenticação com a Google Cloud
            - echo $(shipctl get_integration_resource_field google_cloud JSON_key) > $GCE_CREDENTIALS_FILE_PATH
            - export GOOGLE_APPLICATION_CREDENTIALS=${GCE_CREDENTIALS_FILE_PATH}
            # Chamo o packer
            - packer build official-image.json
    on_sucess:
      script:
        # Versionando a imagem
        - shipctl put_resource_state os_image_version versionName $BUILD_NUMBER
