---
- name: DNS Update
  hosts: localhost
  connection: local
  tasks:
    - name: Updating entry at CloudFlare
      cloudflare_dns:
        zone: lowbit.com.br
        record: "{{ service_name }}-{{ service_env }}"
        type: A
        value: "{{ vm_ip }}"
        solo: true
        account_email: "{{ cloudflare_email }}"
        account_api_token: "{{ cloudflare_api }}"
